"""
Message module for the Agent framework.

PURPOSE:
  In a conversation between a user, an AI, and tools, we need a standardized
  way to represent every "turn". This module provides that representation.

KEY CONCEPTS:
  - MessageRole: Who is speaking? (system, user, assistant, or tool)
  - Message: The actual content + metadata

WHY USE AN ENUM FOR ROLES?
  Using an Enum (instead of raw strings like "system", "user") gives us:
  1. Type safety — we can't accidentally misspell "ASSISTANT"
  2. IDE autocomplete — we get suggestions while typing
  3. Exhaustiveness checking — if we add a new role, Python will warn us
     in all our `match/case` statements

WHY A DATACLASS FOR MESSAGE?
  A dataclass automatically generates __init__, __repr__, __eq__ for us.
  We just declare the fields and Python handles the boilerplate.
  It's much cleaner than writing a manual class.

DESIGN DECISION — WHY NOT INHERIT FROM SOMETHING?
  Message is intentionally simple and "plain". We don't inherit from
  anything because it needs to serialize/deserialize easily for API calls.
  The simpler the structure, the easier it is to convert to JSON or dicts.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Optional

# Explicitly declare what this module exports
# This helps users know exactly what they can import from this module
__all__ = ["Message", "MessageRole"]


class MessageRole(Enum):
    """
    Represents the sender of a message in a conversation.

    Think of this like the "from" field in an email envelope.

    Values:
        SYSTEM: Messages from the system/instructions (e.g., "You are a helpful agent")
        USER: Messages from the end user
        ASSISTANT: Messages generated by the LLM
        TOOL_RESULT: Output from a tool that was executed

    WHY SEPARATE TOOL_RESULT?
      In the ReAct pattern, the LLM thinks and decides to call a tool.
      The tool executes and returns its result. This result is NOT from
      the LLM — it's from an external source. So we give it a distinct
      role to make this clear.
    """
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL_RESULT = "tool_result"


@dataclass
class Message:
    """
    A single message in a conversation.

    Attributes:
        role: Who is sending this message (see MessageRole above)
        content: The actual text content. Can be None for assistant
                 messages that only contain tool calls.
        tool_call: Optional dictionary describing a tool invocation.
                   Example: {"name": "weather", "args": {"city": "Beijing"}}
                   This is used when the LLM decides to use a tool.

    WHY ALLOW content=None?
      In the ReAct pattern, the LLM sometimes outputs a tool call WITHOUT
      any text explanation. The content would be None, and the tool_call
      dict carries all the information. Both approaches are valid.

    RELATION TO OPENAI'S MESSAGE FORMAT:
      This dataclass maps directly to OpenAI's message format:
        {"role": "user", "content": "Hello"}
      The MessageRole.value maps to the "role" string.
    """
    role: MessageRole
    # content is Optional because tool-only messages may not have text
    content: Optional[str] = None
    # tool_call is Optional because most messages don't invoke tools
    tool_call: Optional[dict] = None
